### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by huruji** [hikariyo/blog#1]
我的一个重要项目依赖了您的 json-file-database 这个仓库，但是我近期发现这个仓库好像被删除了，npm包也被删除了，想问大佬是否有可能重新开一下这个仓库呢？

https://blog.hikariyo.net/js/json-file-database/index.html

**Comment by hikariyo** [comment]
不好意思，之前邮箱遇到了一些问题，没有考虑迁移的事项。

https://www.npmjs.com/package/json-file-database

**Comment by hikariyo** [comment]
应该只发布到 NPM 上就可以解决这个问题了吧，我实在是没想到自己学习的小项目还会被引用，所以迁移的时候没有考虑到，非常抱歉 🥲

**Comment by huruji** [comment]
> 应该只发布到 NPM 上就可以解决这个问题了吧，我实在是没想到自己学习的小项目还会被引用，所以迁移的时候没有考虑到，非常抱歉 🥲

@hikariyo  可以的呢，我觉得很好用呀，对比了一下其他包，感觉还是这个好，辛苦大佬有空发布一下？

**Comment by hikariyo** [comment]
已经发布了啊，版本号 `2.0.3` 😳
